plugins:
  - jekyll-feed
  - jekyll-sitemap

# Outputting
permalink: /:year/:month/:title.html
timezone: Asia/Shanghai

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      comments: true
  -
    scope:
      path: ""      # empty string for all files
      type: pages   # limit to posts
    values:
      comments: false

#iLotus configs
iLotus:
  columns: 1
  begin: 2011

  # comments provider
  comments:
    provider: disqus
    duoshuo:
      short_name:
    disqus:
      short_name: isaymesite

  archives_path: /archives.html
  contact_path: /contact.html
  links_path: /links.html
  tags_path: /tags.html

  #菜单配置
  navs:
    - text: 首页
      url: /
      icon: fa fa-home
      class: home
    - text: 文章归档
      url: /archives.html
      icon: fa fa-reorder
      class: none
    - text: 文章标签
      url: /tags.html
      icon: fa fa-tags
      class: none
    - text: 关于我
      url: /contact.html
      icon: fa fa-user
      class: none
    - text: 博客源代码
      url: https://github.com/Wyntau/wyntau.github.io
      icon: fa fa-github-square
      class: none

#站点基础配置
title: 自说Me话
subTitle: I Say Me | 我说我自己 | 我说世界
description: Wyntau's Individual Blog. 自说Me话,一个前端开发新手的网络记录,同喜欢网络,Linux,前端开发,爱折腾的人共同分享,记录折腾心得还有学习过程.
keywords: Wyntau,Linux,Web,前端开发,自说Me话,ISayme,Internet
url: http://isay.me

author:
  name : Wyntau
  email: wyntau@outlook.com
  github: Wyntau
  twitter: Wyntau
  douban: lwent
  QQ: 83692901
  weibo: leftupme
