plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-seo-tag

remote_theme: wyntau/jekyll-theme-iLotus

# Outputting
permalink: /:year/:month/:title.html
timezone: Asia/Shanghai

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      comments: true
  -
    scope:
      path: ""      # empty string for all files
      type: pages   # limit to posts
    values:
      comments: false

#iLotus configs
iLotus:
  columns: 1

comments:
  provider: disqus
  disqus:
    short_name: isaymesite

#站点基础配置
title: 自说Me话
subTitle: I Say Me | 我说我自己 | 我说世界
description: Wyntau's Individual Blog. 自说Me话,一个前端开发新手的网络记录,同喜欢网络,Linux,前端开发,爱折腾的人共同分享,记录折腾心得还有学习过程.
keywords: Wyntau,Linux,Web,前端开发,自说Me话,ISayme,Internet
url: http://isay.me

author:
  name : Wyntau
  email: wyntau@outlook.com
  github: Wyntau
  twitter: Wyntau
  douban: lwent
  QQ: 83692901
  weibo: leftupme
